### ISSUE TITLE
关于框架的一些建议

### ISSUE THREAD

**Issue by yizzuide** [Vegetarians/Lotusoot#10]
为什么不考虑使用OC来作为框架的开发语言呢，OC有强大的Runtime方法，又能同时给OC开发者和Swift开发者使用，不会随新版Swift语法的变动而变动，另外我认为约定优于配置会更好

**Comment by summertian4** [comment]
使用 OC 的好处是可以在 load 方法中解决注册的问题（对于解耦路由来说），Swift 中没有 load 方法，如果没有 load 方法，所以只能另寻其他解决方案，这时 OC 也没有更多的优势。

**Comment by summertian4** [comment]
另外对于『约定优于配置』，对沉淀已久的框架开发是可以的，比如 java 几大常见框架。但是对于 iOS 开发，很少很能见到通用的范式，也很难管理团队内的规范，除了 Code Review，要尽量做到将问题今早暴露，这也是移动端开发往往使用 CI 来保证 PR 合并之前的质量。

**Comment by yizzuide** [comment]
比如：
控制器约定为：组件名+ViewController后辍
业务组件约定为：组件名+Lotusoot后辍
这样不用每新建一个类加一些注解，可以通过注册组件名，再使用反射机制拿到类

**Comment by summertian4** [comment]
约定是不可靠的，现在 Lotusoot 还是使用字串的方式作为注解，和约定基本上没有区别。
但是努力的方向应该是通过能监测的方式作为注解，去掉不可靠因素，约定不能保证不出错，等到闪退就迟了。
