### ISSUE TITLE
继承AccountLotus协议必须实现里面所有代理方法

### ISSUE THREAD

**Issue by Nixiaxia** [Vegetarians/Lotusoot#11]
一个模块继承这个协议后要实现里面的所有的方法，如果有其他模块的方法，是不是应该换成可选类型？

**Comment by summertian4** [comment]
你理解的方式可能恰巧相反了。
并不是『Lotus』里列了多少方法，『Lotusoot』去实现。
而是『Lotus』是声明了模块可以提供多少功能，『Lotusoot』有什么功能，就写什么协议，既然没有某个功能，也就不需要写在『Lotus』里
